project:
  type: website

website:
  title: "Quantitative methods II" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sessions
      - menu:
          - text: "Session 1: OLS"
            href: sessions/session1/session1.qmd
      - text: Exercices
      - menu:
          - text: "Exercices 1: OLS"
            href: exercices/exercices1/exercices1.qmd
      - text: Slides
      - menu:
          - text: "Slides - session 1"
            href: slides/session1/session1.qmd
      - text: Homeworks
      - menu:
          - text: "Homework 1"
            href: homeworks/homework1.qmd
          - text: "Homework 2"
            href: homeworks/homework2.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    tabsets: true

