---
title: "About"
---


Jessica De Rongé holds a Master's degree in Political Science from UCLouvain, obtained in 2021, and a Master's degree in Statistics from UCLouvain, obtained in 2024. Since October 2024, she has been a PhD student at the Centre for European Studies and Comparative Politics (CEE). As part of her PhD research, she investigates citizen trust in various mechanisms of citizen participation, such as mini-publics. Previously, she worked on youth participation in the Youth for Climate movement and on the cultural equivalence of the concept of political efficacy.


Paul Servais holds a degree in Physical Engineering from the Université Libre de Bruxelles (2023) and a Master’s in Governance of Ecological Transitions from the École Urbaine de Sciences Po Paris (2025). In 2025, he worked as a research assistant for Carlo Colombo on the ‘GUD EU Law’ project. He specializes in political science, with a focus on comparative politics. Paul Servais is preparing a PhD in comparative political science, examining the direct and indirect effects of climate change on political behavior in Western Europe. 



