---
title: "Exercices - R basics and OLS regressions"
format: html
---

# Exercice 1 : analysing party positions

The Chapel Hill expert survey data is a survey that 
"provides information about the positioning of the leadership of 279 parties in 31 countries over
the course of 2024 on ideology, policy, populism, democracy, European integration, and select EU
policy questions. Country coverage includes all European Union member states except for
Luxembourg -- plus Iceland, Norway, Switzerland, Turkey, and the United Kingdom.2 The dataset
adopts the country code and party id schema of the CHES Trend file (Jolly et al. 2022) and the
Speed CHES survey on Ukraine (Hooghe et al. 2024) with extensions for newly covered parties" (see [documentation of CHES](https://static1.squarespace.com/static/5975c9bfdb29d6a05c65209b/t/69163d62e2606b5a3c46812b/1763065186525/CHES+2024+Codebook.pdf)). 

You can find the recent survey's dataset on the internet at <https://www.chesdata.eu/s/1999-2024_CHES_dataset_means.csv>, to perform the following tasks :  

  1. Import the data in your local environment. Use the `rio` package and library to import it directly from the internet. 
  2.  Use the glimpse() function to have a look at your data
  3.  Filter the data set to only keep the most recent year, 2024.
  4.  Using the identifiers and general information in the documentation, keep only the following items:"country", "the overall ideology on a scale ranging from 0 (extreme left) to 10 (extreme right)", "Thinking about the European Union's relationship with Russia, where do you place each party on its preferred action for European countries to take?", "Position on civil liberties VS. law and order", "Position on same sex marriage", "position on urban-rural", "position on nationalism", "left-right positioning". 
  5.  Summarize three of these variables and comment on your findings.
  6.  You now want to more specifically understand what drives a party to adopt favorable or more defavorable stances on the EU's relationship with Russia. What would be your dependent variable ? Plot a histogram of this DV and comment on the distribution.
  7. You want to understand if left-right positioning influences the EU-Russia position of a party:
    - draw a scatter plot of the two variables, using `ggplot2` and `geom_point()`, and add the regression line. 
    - run a simple linear regression model, with EU-Russia as dependent variable, and left-right positioning of a party as independent variable. Display the regression table using `stargazer` and interpret the coefficients. Do you think this result could be biased ? If so, why ? How could you correct that ?
   - Run a multiple linear regression to understand whether adding the party's position on nationalism changes something. Store the value in another model, so that you can compare both in the same `stargazer` table. What do you observe ? Compare the values `lrgen` in both tables and comment on those.
   - Run a last linear regression with the party's left-right position, his urban-rural position, his position on same sex marriage, and use the binary variable east-west to know if being East or West changes your party's position. What can you conclude ? Now add nationalism among the independent variables and comment? What is the best model ? 
  8. Now imagine wondering whether being in a country from Eastern or Western Europe influences how nationalism influences your position on this issue. How could you test that ? Plot the predicted values.
  9. Compute a last, fully saturated model, with all your variables except `country`, and run tests of multicollinearity and heteroskedasticity. What do you find ? Comment on the results. Add `as.factor(country)` in the regression and comment on the results.

```{r}
#| echo: false
#| eval: false
library(rio)
library(tidyverse)
library(stargazer)
ches <- import("https://www.chesdata.eu/s/1999-2024_CHES_dataset_means.csv")
#glimpse(ches)
ches <- ches %>% filter(year == 2024)
ches <- ches %>% select(country, eastwest, eu_russia, civlib_laworder, samesex_marriage, nationalism, urban_rural, lrgen)
summary(ches)
hist(ches$eu_russia)

ggplot(data = ches, aes(x= lrgen, y = eu_russia)) + geom_point() +geom_smooth(method = "lm")

model<- lm(data = ches, eu_russia ~ lrgen)
summary(model)
model2 <- lm(data = ches, eu_russia ~ lrgen + nationalism)
model3 <- lm(data = ches, eu_russia ~eastwest+ lrgen + urban_rural+ samesex_marriage)
model4 <- lm(data = ches, eu_russia ~eastwest+ lrgen + urban_rural+ samesex_marriage + nationalism)
model5 <- lm(data = ches, eu_russia ~eastwest*nationalism)
stargazer(model, model2,model3, model4,model5,
          title = "EU - Russia results", 
          align = TRUE, 
          type = "text")

library(ggeffects)

ggpredict(model5, terms = c("nationalism", "eastwest")) |>
  as_tibble() |>
  mutate(
    group = factor(
      group,
      levels = c("1", "0"),
      labels = c("East", "West")
    )
  ) |>
  ggplot(aes(x = x, y = predicted, color = group, fill = group)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = 0.2)+ labs(x = "Nationalism", y ="Predicted position on EU-Russia")

model6 <- lm(data = ches, eu_russia ~ nationalism + civlib_laworder+ eastwest+ samesex_marriage + urban_rural + lrgen)

library(performance)
map(list(model6), check_collinearity)
check_heteroscedasticity(model6) # Run a Breush-Pagan test

```
# Exercice 2 : Comparing electoral outcomes in the French elections
You are provided with data about the legislative and the presidential elections in France, in 2022, as well as socio-demographic data on French communes in 2022, for LR (coded as "right") and RN ("far-right"). You are asked to :

1. Knowing that the data can be accessed online through URLs <> and <>, import the data in RStudio.
2. 


# Exercice 3 - 

